#!/usr/bin/env bash
# sync-docs.sh — clone honojs/website and convert its VitePress markdown
# sources into skill reference files under references/docs/.
#
# Each generated file gets a YAML frontmatter block pointing back to the
# GitHub source and the live hono.dev URL so an AI using this skill can
# decide whether to fetch the latest version.
#
# Usage: bash scripts/sync-docs.sh [--ref main]
#
# Designed to run in CI (see .github/workflows/sync-docs.yml) or locally.

set -euo pipefail

REF="main"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --ref) REF="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
DOCS_OUT="$SKILL_DIR/references/docs"

REPO_URL="https://github.com/honojs/website"
WORK_DIR="$(mktemp -d -t hono-website-XXXXXX)"
trap 'rm -rf "$WORK_DIR"' EXIT

echo "→ Cloning $REPO_URL@$REF into $WORK_DIR"
git clone --depth 1 --branch "$REF" "$REPO_URL" "$WORK_DIR/website" >/dev/null 2>&1

SRC_DOCS="$WORK_DIR/website/docs"
if [[ ! -d "$SRC_DOCS" ]]; then
  echo "ERR: $SRC_DOCS missing — upstream layout may have changed." >&2
  exit 1
fi

COMMIT_SHA="$(git -C "$WORK_DIR/website" rev-parse HEAD)"
SYNCED_ON="$(date -u +%Y-%m-%d)"

# Wipe prior output so upstream deletions propagate.
rm -rf "$DOCS_OUT"
mkdir -p "$DOCS_OUT"

# Transform: strip any upstream YAML frontmatter, then convert VitePress
# `:::` containers. Tip/info/warning/danger become blockquote headers so
# semantics survive. code-group / details lose their wrapper (the inner
# code fences stand on their own in plain markdown). `[label]` suffixes
# on code fences (```sh [npm]`) are left as-is — harmless in renderers
# that don't know VitePress, and useful context for a reader.
transform() {
  awk '
    # Strip leading YAML frontmatter (only docs/index.md has one upstream).
    NR == 1 && /^---[[:space:]]*$/ { in_fm = 1; next }
    in_fm && /^---[[:space:]]*$/  { in_fm = 0; next }
    in_fm                          { next }

    # VitePress container opener.
    /^:::[[:space:]]*(tip|info|warning|danger|code-group|details)([[:space:]]+.*)?$/ {
      label = $0
      sub(/^:::[[:space:]]*/, "", label)
      kind = label
      sub(/[[:space:]].*$/, "", kind)
      rest = label
      sub(/^[^[:space:]]+[[:space:]]*/, "", rest)
      if (kind == "tip" || kind == "info" || kind == "warning" || kind == "danger") {
        upper = toupper(substr(kind, 1, 1)) substr(kind, 2)
        if (rest == "") print "> **" upper "**"
        else            print "> **" upper ":** " rest
      }
      next
    }
    # VitePress container closer.
    /^:::[[:space:]]*$/ { next }

    { print }
  ' "$1"
}

count=0
while IFS= read -r -d '' src; do
  rel="${src#"$SRC_DOCS"/}"              # e.g. getting-started/basic.md
  out="$DOCS_OUT/$rel"
  mkdir -p "$(dirname "$out")"

  github_url="https://github.com/honojs/website/blob/$REF/docs/$rel"

  # Per-file frontmatter is intentionally minimal: just `source:`.
  # The sync date and upstream commit are the same for every file in a
  # batch — they live in `_manifest.md` once, not in 84 headers. The
  # raw URL for fetching is a deterministic transform of `source:` (swap
  # `/blob/` for `/raw/`), explained in SKILL.md.
  {
    printf -- '---\n'
    printf -- 'source: %s\n' "$github_url"
    printf -- '---\n\n'
    transform "$src"
  } > "$out"
  count=$((count + 1))
done < <(find "$SRC_DOCS" -type f -name '*.md' -print0)

# Write a sync manifest so humans (and AI) can see what version we're on.
{
  printf -- '---\n'
  printf -- 'source_repo: %s\n' "$REPO_URL"
  printf -- 'ref: %s\n' "$REF"
  printf -- 'upstream_commit: %s\n' "$COMMIT_SHA"
  printf -- 'synced: %s\n' "$SYNCED_ON"
  printf -- 'file_count: %d\n' "$count"
  printf -- '---\n\n'
  printf -- '# Hono docs sync manifest\n\n'
  printf -- 'This directory is generated by `scripts/sync-docs.sh` from %s at commit `%s`.\n\n' "$REPO_URL" "$COMMIT_SHA"
  printf -- 'Do not edit files here by hand — changes are overwritten on the next sync. Open a PR against the upstream repo instead:\n\n'
  printf -- '  %s\n' "$REPO_URL"
} > "$DOCS_OUT/_manifest.md"

echo "✓ Synced $count files into $DOCS_OUT (upstream @ ${COMMIT_SHA:0:7})"
